version: '3'
services:
  mongodb:
    image: 'mongo:latest'
    ports:
      - "27017:27017"

  coinnews:
    image: amirhossein21/coinnews.linux:v0.2
    ports:
      - "8000:8000"
    volumes:
      - ./coinnews/config.yml:/go/src/app/config.yml

  bepa:
    build:
      context: ./Bepa
      dockerfile: Dockerfile
    volumes:
      - /usr/app/node_modules
      - ./Bepa:/usr/app
    command: >
      sh -c "while true; do npm run start; sleep 10; done"

  peyk:
    build:
      context: ./Peyk
      dockerfile: Dockerfile
    volumes:
      - /usr/app/node_modules
      - ./Peyk:/usr/app
    ports:
      - "3000:3000"
